---
title: "Assignment 4 Task 2"
author: "Alia Ajina"
date: "11/3/2021"
output: html_document
---

## Overview

## Setup


```{r setup, include=TRUE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(lubridate)
library(kableExtra)
```

## Read in Bonanza Creek Hares data

```{r}
bonanza <- read_csv(here("data", "bonanza_hares.csv"))
```

## Data Wrangling

```{r}
juvenile_hare <- bonanza %>% 
filter(age == "j") %>% 
mutate(date = mdy(date)) %>% 
mutate(year = year(date)) %>% 
group_by(year) %>% 
summarise(count=n())
  
```

## Summary Statistics??? do i need to do this?

Summarize the data and create a summary table with kableExtra.

```{r}
# Create table of summary stats
juvenile_hare_table <- juvenile_hare %>% 
  summarise(mean = round(mean(size), 2), 
            median = median(size), 
            sd = round(sd(size), 2))

# Use kableExtra to finalize table
 
juvenile_hare_table %>% 
kable(col.names = c("Count", 
                      "Mean Count",
                      "Median Count ",
                      "Standard Deviation",
                      "Sample Size"),
        caption = "<center>Table 1: Summary Statistics of Purple Sea Urchins at Naples Reef in 2010<center>") %>% 
  kable_styling(bootstrap_options = "bordered",
                full_width = FALSE, position = "center")
```

## Data Visualization


```{r}
# Create bar graph
ggplot(data = juvenile_hare, 
       aes(x = year, y = count, fill = count)) +
# Change aesthetics accordingly
  geom_col() +
  theme_minimal() +   
  scale_x_continuous(breaks = c(1999, 2000, 2001, 2003, 2004, 2005, 2006, 2007, 2008, 2010, 2011, 2012 )) +
  scale_y_continuous(breaks = c(0, 20, 40, 60, 80, 100, 120, 140)) +
  labs( x = "Year",
        y = "Number of Juvenile Hares",
        title = " Distribution of Juvenile Hares fron 1999 - 2012 (AJINA)",
        caption = "Figure 1.1: ") +
# Adjust positioning
  theme(axis.text.x = element_text(size = 6, hjust = 0.6, angle = 50),
        axis.text.y = element_text(size = 6),
        axis.title.x = element_text(hjust = 0.5, 
                                    vjust = 0.5),
        plot.title = element_text(hjust = .5), 
        plot.subtitle = element_text(hjust = .5),
        plot.caption = element_text(hjust = .2), 
        legend.position = "none")
```
